### ISSUE TITLE
How is Configuration DataSource?

### ISSUE THREAD

**Issue by alexisaraya** [n-at/arbirter#1]
How is the datasource configured? Should it be the same datasource that is in the report?

Sprint boot config in  application.properties, but no sure is something else is needed

Tranks, and good job

**Comment by n-at** [comment]
There is no need to configure Spring Boot datasource, report datasource will be enough.

**Comment by alexisaraya** [comment]
The data source in the reports is a JDNI, to pass the parameters dynamically.

**Comment by n-at** [comment]
I'm afraid I can't help with this - I only used JDBC datasources in my reports.
